
/*
 This file was autogenerated via
 ---------------------------------
 ldetool --go-string versioned.lde
 ---------------------------------
 do not touch it with bare hands!
*/

package replacer

import (
	"fmt"
	"strconv"
	"strings"
)

// Suffix ...
type Suffix struct {
	Rest  string
	Major int
}

// Extract ...
func (p *Suffix) Extract(line string) (bool, error) {
	p.Rest = line
	var err error
	var pos int
	var tmp string
	var tmpInt int64

	// Checks if the rest starts with 'v' and pass it
	if len(p.Rest) >= 1 && p.Rest[0] == 'v' {
		p.Rest = p.Rest[1:]
	} else {
		return false, nil
	}

	// Take until '/' (or all the rest if not found) as Major(int)
	pos = strings.IndexByte(p.Rest, '/')
	if pos >= 0 {
		tmp = p.Rest[:pos]
		p.Rest = p.Rest[pos+1:]
	} else {
		tmp = p.Rest
		p.Rest = p.Rest[len(p.Rest):]
	}
	if tmpInt, err = strconv.ParseInt(tmp, 10, 64); err != nil {
		return false, fmt.Errorf("parsing `%s` into field Major(int): %s", tmp, err)
	}
	p.Major = int(tmpInt)

	return true, nil
}
